### ISSUE TITLE
코드 지속적 배포 설정

### ISSUE THREAD

**Issue by NaamuKim** [cbnu-sequence/anonymous-backend#1]
## TODO

- develop 브랜치 
  - [ ] 병합 시 빌드 후 S3에 업로드
  - [ ] S3에 업로드 된 내용을 바탕으로 배포 

- master 브랜치 
  - [ ] 병합 시 빌드 후 S3에 업로드
  - [ ] S3에 업로드 된 내용을 바탕으로 배포
